personalTrainer/personalTrainer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('trainingApp.urls')),
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    ]
    # ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalTrainer/trainingApp/urls.py
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

app_name = 'trainingApp'

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^clients/$', views.ClientsListView.as_view(), name='clients'),
    url(r'^allSchedules/$', views.ClientsWorkOutSchdListView.as_view(), name='allSchedules'),
    url(r'^(?P<pk>[0-9]+)/clientWeightIns/$', views.ClientsDetailView.as_view(), name=
    'clientWeightIns'),
    url(r'^(?P<pk>[0-9]+)/clientWorkOutSchd/$', views.ClientWorkOutSchdDetail.as_view(), name=
    'clientWorkOutSchd'),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalTrainer/trainingApp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class Client(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_joined = models.DateTimeField(auto_now=True, blank=False, editable=False)
    email = models.EmailField(max_length=100, unique= True)
    initial_weight = models.FloatField(default=0)
    # urer = models.ForeignKey(User, on_delete=models.SET_NULL)

    class Meta:
        ordering = ["-first_name"]

    def get_absolute_url(self):
        return reverse("clients", kwargs={"first_name": self.id})

    def __str__(self):
        return('{} {}' .format(self.first_name, self.last_name))

    def was_client_added_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_joined <= now
        was_client_added_recently.admin_order_field = 'date_joined'
        was_client_added_recently.boolean = True
        was_client_added_recently.short_description = 'Added recently?'

class WeightIn(models.Model):
    '''Represent one appointment with one client with the trainer.'''
    name_of_client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date_weighted = models.DateTimeField(blank=True)
    weight = models.FloatField(blank=True)
    # TODO Float Validation, check that is a float not chars.

    class Meta:
        ordering = ['-weight']

    def __str__(self):
        '''Returns the information of the client's weight and data taken.'''
        return('{} {}' .format(self.weight, self.date_weighted))

        # This was incase the client wasn't being displayed correctly.
    # def display_client(self):
    #     return ', '.join([client.first_name for client in self.client.all()])
    # display_client.short_description = 'Client'

class WorkOutSchedule(models.Model):
    ''' Represent schedules for the client that will workout.'''
    name_of_client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date_WO = models.DateField(blank=True)
    time_of_day = models.TimeField(blank=True)
    # TODO Validation if user already has a scheduled date and time.
    # TODO Past date/tie validation error, make sure user enters future dates.

    WEEK_SCHEDULE = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    )
    schedule = models.CharField(max_length=30, choices=WEEK_SCHEDULE, default='Monday', help_text='Day of week availability')

    class Meta:
        ordering = ['-date_WO']

    def __str__(self):
        return('{} {} {} {}' .format(self.date_WO, self.schedule, self.time_of_day, self.name_of_client.id))

class UserSignUp(models.Model):
    username = models.ForeignKey(User, blank=False)
    raw_password = models.CharField(max_length=30)
    user = authenticate(username=username, password=raw_password)

personalTrainer/trainingApp/forms.py
from django.db import models
from django.forms import ModelForm


class SignUpForm(models.Model):
     class Meta:
         model = Article
         fields = ['pub_date', 'headline', 'content', 'reporter']

personalTrainer/trainingApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.views import generic

from django.contrib.auth import authenticate, logout, login, REDIRECT_FIELD_NAME
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from personalTrainer import settings

from django.shortcuts import render_to_response, redirect
from django.utils.decorators import method_decorator
from .models import Client, WeightIn, WorkOutSchedule


def home(request):
    ''' Home page same as Index page'''
    num_of_clients = Client.objects.all().count()
    num_of_workouts = WorkOutSchedule.objects.all().count()
    return render(request, 'trainingApp/home.html', context={'num_of_clients': num_of_clients, 'num_of_workouts': num_of_workouts})



class ClientsListView(generic.ListView):
    # Display the clients list.
    template_name = 'trainingApp/clients.html'
    context_object_name = 'list_of_clients'

    def get_queryset(self):
        """Return all the objects in the clients table."""
        return Client.objects.order_by('first_name')

class ClientsDetailView(generic.DetailView):
    # WeightIns details
    model = Client
    template_name = 'trainingApp/clientWeightIns.html'

class ClientsWorkOutSchdListView(generic.ListView):
    template_name = 'trainingApp/all_WOSchedules.html'
    context_object_name = 'list_of_WOSchedules'

    def get_queryset(self):
        return WorkOutSchedule.objects.order_by('date_WO')

class ClientWorkOutSchdDetail(generic.DetailView):
    model = Client
    template_name = 'trainingApp/clientWorkOutSchd.html'


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('trainingApp/home')
        else:
            form = SignUpForm()
            return render(request, 'trainingApp/signup.html', {'form': form})

def login(request):
    next = request.GET.get('next', '/home/')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(next)
        else:
            return HttpResponse("Account is not active at the moment.")
    else:
        return HttpResponseRedirect(settings.LOGIN_URL)
        return render(request, "trainingApp/login.html", {'next': next})

personalTrainer/trainingApp/templates/trainingApp/all_WOSchedules.html
{% extends 'trainingApp/base.html' %}
{% load static %}
{% block content %}
    {% if list_of_WOSchedules %}
        <table class="table">
        <h2>This is this list of all the work schedules with the client's name</h2>
        <thead>
          <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Day</th>
            <th>Fullname</th>
          </tr>
        </thead>
        <tbody>
        {% for dates in list_of_WOSchedules %}
        <tr>
    	 	<td>{{ dates.date_WO }}</td>
            <td><strong>{{ dates.time_of_day }}</strong></td>
            <td>{{ dates.schedule }}</td>
			<td>{{ dates.name_of_client.first_name }} {{ dates.name_of_client.last_name }}</td>
        </tr>
        {% endfor %}
        </tbody>
    {% else %}
        <p>No schedules in the list.</p>
    {% endif %}
{% endblock %}

personalTrainer/trainingApp/templates/trainingApp/base.html
{% load i18n static %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
	<link href="{% static 'trainingApp/css/bootstrap.min.css' %}" rel="stylesheet" type = "text/css"/>
	<link href="{% static 'trainingApp/js/bootstrap.min.js' %}">
	<link rel="stylesheet" href="{% static 'traningApp/css/styles.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<title>
		{% block title %}
		{% endblock title %}
	</title>
	<style media="screen">
	#document-floating {
		min-height:500px;
		_height:500px;
		font-size:200%;
	}
	.sidebar-nav {
	    margin-top: 20px;
	    padding: 0;
	    list-style: none;
	}
	</style>


</head>
<body>
	<div class="container-fluid">
	    <div class="row">
	      <div class="col-sm-2">
	      {% block sidebar %}
		  <hr>
		  <ul class="sidebar-nav">
			  <strong>
	          <li><a href="{% url 'trainingApp:home' %}">Home</a></li><br>
	          <li><a href="{% url 'trainingApp:clients' %}">All Clients</a></li><br>
	          <li><a href="{% url 'trainingApp:allSchedules' %}">All WorkOut Schedules</a></li><br>
			  </strong>
			  {% if user.is_authenticated %}
			     <li>User: {{ user.get_username }}</li>
			     <li><a href="{% url 'logout'%}">Logout</a></li>
				 <!-- <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li> -->
			   {% else %}
			   	<li><a href="{% url 'login'%}">Login</a></li>
			     <!-- <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li> -->
			   {% endif %}
      	  </ul>
	     {% endblock %}
	      </div>
	      <div class="col-sm-10 ">
			  <hr>
	      {% block content %}

		  {% endblock %}
	      </div>
	    </div>
	 </div>
</body>
</html>

personalTrainer/trainingApp/templates/trainingApp/clientWeightIns.html
{% extends 'trainingApp/base.html' %}
{% load static %}

{% block content %}
<!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->
	<table class="table">
		<p>Here are the weight records for</p>
		<h2><strong>{{ client.first_name }}  {{ client.last_name}}</strong></h2>
		<thead>
			<tr>
				<th>Date</th>
				<th>Weight</th>
			</tr>
		</thead>
		<tbody>
		{% for detail in client.weightin_set.all %}
			<!-- <input type="radio" name="detail" id="detail{{ forloop.counter }}" value="{{ detail.id }}" /> -->
			<!-- <tr for="detail{{ forloop.counter }}"> -->
			<tr>
				<td>{{ detail.date_weighted }}</td>
				<td>{{ detail.weight }}</td>
			</tr><br/>
		</tbody>

		{% endfor %}
	</table>
{% endblock %}


<!--
<form action="{% url 'trainingApp:stars' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Stars" />
</form>
 -->

personalTrainer/trainingApp/templates/trainingApp/clientWorkOutSchd.html
{% extends 'trainingApp/base.html' %}
{% load static %}

{% block content %}
	<!-- <h2>{{ dates.time_of_day }}</h2> -->
	<!-- <h2>{{ client.first_name }}  {{ client.last_name }}</h2> -->
	<!-- <li><strong>Clients:</strong> {{ num_of_clients }}</li> #optional -->
	<table class="table">
		<p>This are the training schedules for:</p>
		<h2><strong>{{ client.first_name }}  {{ client.last_name}}</strong></h2>
		<li><strong>Total Work Out Schedules:</strong> {{ num_of_workouts }}</li>
		<thead>
			<tr>
				<th></th>
				<th>Day</th>
				<th>Time</th>
				<th>Date</th>
			</tr>
		</thead>
		<tbody>
		{% for detail in client.workoutschedule_set.all %}
		<!-- <input type="radio" name="detail" id="detail{{ forloop.counter }}" value="{{ detail.id }}" /> -->
			<!-- <tr for="detail{{ forloop.counter }}"> -->
			<tr>
				<td>Scheduled for</td>
				<td>{{ detail.schedule }}</td>
				<td>{{ detail.time_of_day }}</td>
				<td>{{ detail.date_WO }}</td>
			</tr>
		{% endfor %}
		</tbody>
{% endblock %}

personalTrainer/trainingApp/templates/trainingApp/clients.html
{% extends 'trainingApp/base.html' %}
{% load static %}
{% block content %}
    {% if list_of_clients %}
        <table class="table">
        <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
            <th>Date Joined</th>
            <th>Original Weight</th>
            <th>Link-WeghtRecords</th>
            <th>Link-WO-schedule</th>
          </tr>
        </thead>
        <tbody>
        {% for client in list_of_clients %}
		 <tr>
            <td>{{ client.first_name }}</td>
            <td>{{ client.last_name }}</td>
            <td>{{ client.email }}</td>
            <td>{{ client.date_joined }}</td>
            <td>{{ client.initial_weight }}</td>
		  	<td><a href="{% url 'trainingApp:clientWeightIns' client.id %}"><u>Weight records</u></a></td>
            <td><a href="{% url 'trainingApp:clientWorkOutSchd' client.id %}"><u>WorkOut Schedule</u></a></td>
        </tr>
        {% endfor %}
        </tbody>
    {% else %}
        <p>No clients in the list.</p>
    {% endif %}
{% endblock %}

personalTrainer/trainingApp/templates/trainingApp/home.html
{% extends 'trainingApp/base.html' %}
{% load static %}
{% block title %}Home page{% endblock title %}

{% block content %}
<h1>Welcome to the trainingApp</h1>
 {% if user.is_authenticated %}
    {% if user.is_superuser %}
        <h2>Welcome <strong>super</strong> user</h2>
        <ul>Number of clients: <strong>{{ num_of_clients }}</strong></ul>
    {% endif %}
    {% else %}
     <li>Welcome <strong>{{ user.get_username }}</strong> click on the link below</li>
     <h2>{{ client.first_name }}  {{ client.last_name }}</h2>
     <li><strong>Clients:</strong> {{ num_of_clients }}</li>
     {% for detail in client.workoutschedule_set.all %}
     <!-- <input type="radio" name="detail" id="detail{{ forloop.counter }}" value="{{ detail.id }}" /> -->
     <h3>
     <li><strong>Work Out Schedules:</strong> {{ num_of_workouts }}</li>
     <tr for="detail{{ forloop.counter }}">
     Schedule for : {{ detail.schedule }}  {{ detail.date_WO }} at
     {{ detail.time_of_day }}

     </tr><br/>
     </h3>
     {% if empty %}
     <p>{{ user.get_username }}, you don't have any training schedule.</p>
     {% endif %}
    {% endfor %}
 {% endif %}
{% endblock %}

personalTrainer/trainingApp/templates/trainingApp/signup.html
{% extends 'training/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
    <!-- <script>
    function submit() {document.forms["form"].submit();}
    </script> -->
{% endblock %}